services:
  - type: web
    name: botishla
    env: python
    region: oregon  # Render'da eng yaqin serverlardan biri
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false
